a=input("Ingrese un numero Entero: ")
a=int(a)
print(a)
print(type(a))
b=input("Ingrese un numero Flotamte: ")
b=float(b)
print(b)
print(type(b))
c=input("Ingrese un Boolenao: ")
c=bool(c)
print(c)
print(type(c))
d=input("Ingrese un char: ")
d=str(d)
print(d)
print(type(d))
e=input("Ingrese un String: ")
print(e)
print(type(e))